alias nick='ssh nick@nick-linux'
alias dave='ssh dave@dave-linux'
alias stacy='ssh stacy@stacy-linux'
alias louis='ssh louis@louis-linux'
alias t306='ssh development@ttraflonrh306'
alias d183='ssh starling_metals@dtraflocorh183'
alias d184='ssh starling_metals@dtraflocorh184'
alias d674='ssh starling_metals@dtraflonrh674'
alias d185='ssh development@dtraflocorh185'
alias p188='ssh production@ttraflocorh188'
alias p195='ssh production@ttraflocorh195'
alias p196='ssh starling_metals@ttraflonrh196'
alias p197='ssh production@ttraflocorh197'
alias d190='ssh development@dtraflocorh190'
alias d198='ssh development@dtraflocorh198'
alias j6='export JAVA_HOME=/usr/local/jdk6/'
alias j7='export JAVA_HOME=/usr/local/jdk7/'
alias sox='ssh -f -N -D 6666 $CAGE'
alias traf-git='git config user.name Alex.McGuire && git config user.email alex.mcguire@trafigura.com'
alias jviz='$JAVA_HOME/bin/jvisualvm '
alias squirrel='nohup ~/bin/squirrel/squirrel-sql.sh 0<&- &> /home/alex/bin/logs/squirrel.log &'
alias solaris='ssh -t titan@etraflocoux138.europe.trafeng.net "cd /opt/starling_metals; exec \$SHELL"'
export JAVA_HOME=/usr/local/jdk7/
alias scla='/usr/local/scala-2.10.2/bin/scala'
alias sng='synergys -c $HOME/synergy.conf'
